name: Github Actions 1
on:
  push:

jobs:
  checkout_to_code:
    uses: ./.github/workflows/reusable-workflow-1.yml
    with:
      name: Teja
    secrets:
      secret_key: ${{ secrets.SECRET_KEY }}
