name: Reusable Workflow 1

on:
  workflow_call:
    inputs:
      name:
        description: 'Name of the person'
        required: true
        default: 'Teja'
        type: string
    secrets:
      secret_key:
        description: 'Secret key'
        required: true

    
jobs:
  job_1:
    runs-on: self-hosted
    steps:
      - name: Print Hello world
        run: echo "Hello world from reusable workflow 1 job 1"
  job_2:
    needs: [job_1]
    runs-on: self-hosted
    steps:
      - name: Print Name
        run: echo "Name- ${{ inputs.name }}, Secret-${{ secrets.secret_key }} reusable workflow 1 job 2"
  job_4:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [job_3]
    steps:
      - name: Print Hello world
        run: echo "Hello world!" > $GITHUB_STEP_SUMMARY