name: Reusable Workflow 1

on:
  workflow_call:
    
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello world
        run: echo "Hello world from reusable workflow 1 job 1"
  job_2:
    needs: [job_1]
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello world
        run: echo "Hello world from reusable workflow 1 job 2"
  job_3:
    needs: [job_2]
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello world
        run: echo "Hello world from reusable workflow 1 job 2"
  job_4:
    runs-on: ubuntu-latest
    needs: [job_3]
    steps:
      - name: Print Hello world
        run: echo "Hello world!" > $GITHUB_STEP_SUMMARY